dbt_project:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: CW
      port: 1433
      database: dbtProject
      schema: dbt_ceci
      windows_login: True
      trust_cert: True

    test:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: CW
      port: 1433
      database: dbtProject
      schema: test
      windows_login: True
      trust_cert: True
    
    production:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: CW
      port: 1433
      database: dbtProject
      schema: dbo
      windows_login: True
      trust_cert: True
